In [1]:
%matplotlib inline

%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [2]:
from q1_softmax import *

In [32]:
np.sum(softmax(k), axis=0)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
k = np.random.randint(1,15,(100,10))

In [27]:
np.sum(k, axis=1).shape

(100,)

In [49]:
test_softmax_basic()

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!



In [58]:
softmax(np.array([[54,55],[3,4]]))

array([[ 0.26894142,  0.73105858],
       [ 0.26894142,  0.73105858]])

In [68]:
k = np.random.randint(1,5,(4,5))

In [69]:
k

array([[1, 3, 4, 3, 3],
       [3, 3, 2, 3, 3],
       [4, 1, 1, 2, 4],
       [4, 3, 3, 4, 4]])

In [70]:
k - np.max(k,axis=1).reshape(-1,1)

array([[-3, -1,  0, -1, -1],
       [ 0,  0, -1,  0,  0],
       [ 0, -3, -3, -2,  0],
       [ 0, -1, -1,  0,  0]])

In [66]:
from q2_sigmoid import *

In [72]:
-sigmoid(k)

array([[-0.73105858, -0.95257413, -0.98201379, -0.95257413, -0.95257413],
       [-0.95257413, -0.95257413, -0.88079708, -0.95257413, -0.95257413],
       [-0.98201379, -0.73105858, -0.73105858, -0.88079708, -0.98201379],
       [-0.98201379, -0.95257413, -0.95257413, -0.98201379, -0.98201379]])

In [66]:
sigmoid_grad(sigmoid(k))

array([[ 0.01766271,  0.19661193,  0.01766271,  0.01766271,  0.19661193],
       [ 0.10499359,  0.10499359,  0.19661193,  0.19661193,  0.19661193],
       [ 0.04517666,  0.10499359,  0.10499359,  0.10499359,  0.01766271],
       [ 0.19661193,  0.04517666,  0.01766271,  0.19661193,  0.01766271]])

In [96]:
test_sigmoid_basic()

Running basic tests...
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]
You should verify these results by hand!



In [5]:
it = np.nditer(k, flags = ['multi_index'], op_flags = ['readwrite'])

In [12]:
it.finished

False

In [34]:
it.multi_indexx

(2, 0)

In [35]:
it.iternext()

True

In [97]:
from q2_gradcheck import *

In [98]:
sanity_check()


Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!



In [47]:
l = np.zeros_like(k, dtype = 'float64')

In [63]:
k.shape

(4, 5)

In [65]:
np.sum(k, axis=0).shape

(5,)

In [99]:
from q2_neural import *

In [122]:
sanity_check()

Running sanity check...
Gradient check passed!


In [4]:
from q3_word2vec import *

In [5]:
test_normalize_rows()

Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]



In [33]:
test_word2vec()

==== Gradient check for skip-gram ====
(5, 9) (5, 3)


ValueError: operands could not be broadcast together with shapes (9,) (3,) (9,) 

In [6]:
predicted = np.random.randint(0,5,(15))
target = 2
outputVectors = np.random.randint(0,5,(50,15))
dataset = np.zeros((1,1))

In [7]:
outputVectors[target].dot(predicted)

68

In [117]:
c, gp, p = softmaxCostAndGradient(predicted,target, outputVectors, dataset )

In [118]:
print gp.shape, p.shape

(15,) (50, 15)


In [8]:
dataset = type('dummy', (), {})()
def dummySampleTokenIdx():
    return random.randint(0, 4)

def getRandomContext(C):
    tokens = ["a", "b", "c", "d", "e"]
    return tokens[random.randint(0,4)], \
        [tokens[random.randint(0,4)] for i in xrange(2*C)]
dataset.sampleTokenIdx = dummySampleTokenIdx
dataset.getRandomContext = getRandomContext

In [67]:
K=10

In [15]:
dataset.getRandomContext(4)

('e', ['c', 'e', 'e', 'c', 'd', 'c', 'e', 'e'])

In [9]:
indices = [target]
indices.extend(getNegativeSamples(target, dataset, 10))

In [78]:
a,b,c = negSamplingCostAndGradient(predicted, target, outputVectors, dataset,   K=10)

In [79]:
print a.shape, b.shape, c.shape

() (15,) (50, 15)


In [80]:
outputVectors[indices] += np.ones((11, 15), dtype='int')

In [81]:
outputVectors[indices]

array([[11, 10, 14, 13, 12, 12, 11, 14, 10, 11, 10, 14, 11, 14, 11],
       [14, 14, 13, 11, 14, 11, 14, 14, 10, 13, 10, 14, 12, 11, 11],
       [10, 11, 11, 12, 12, 13, 10, 12, 10, 12, 11, 13, 11, 13, 11],
       [14, 14, 13, 11, 14, 11, 14, 14, 10, 13, 10, 14, 12, 11, 11],
       [14, 14, 13, 11, 14, 11, 14, 14, 10, 13, 10, 14, 12, 11, 11],
       [10, 11, 11, 12, 12, 13, 10, 12, 10, 12, 11, 13, 11, 13, 11],
       [13, 14, 10, 11, 11, 13, 13, 10, 12, 12, 13, 12, 11, 14, 12],
       [14, 14, 13, 11, 14, 11, 14, 14, 10, 13, 10, 14, 12, 11, 11],
       [10, 11, 11, 12, 12, 13, 10, 12, 10, 12, 11, 13, 11, 13, 11],
       [14, 14, 13, 11, 14, 11, 14, 14, 10, 13, 10, 14, 12, 11, 11],
       [10, 11, 11, 12, 12, 13, 10, 12, 10, 12, 11, 13, 11, 13, 11]])

In [25]:
1 -sigmoid(1e-2)

0.49750002083312506

In [25]:
indices

[2, 1, 3, 3, 4, 0, 1, 3, 3, 1, 0]

In [27]:
predicted.shape

(15,)

In [56]:
np.multiply(predicted,sigmoid(outputVectors[indices].dot(predicted)))  

ValueError: operands could not be broadcast together with shapes (15,) (11,) 

In [68]:
(np.tile(predicted, K+1).reshape(K+1,predicted.shape[0])*sigmoid(outputVectors[indices].dot(predicted)).reshape(-1,1)).shape

(11, 15)

In [69]:
predicted.shape[0]

15

In [119]:
test_word2vec()

==== Gradient check for skip-gram ====
Gradient check failed.
First gradient error found at index (0, 0)
Your gradient: -1.888750 	 Numerical gradient: 0.000000
Gradient check failed.
First gradient error found at index (0, 0)
Your gradient: 5.891767 	 Numerical gradient: -3.357424

==== Gradient check for CBOW      ====
Gradient check passed!
Gradient check passed!

=== Results ===
(array([ 0.]), array([[  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [-10.08506404,  -2.55011757,  -2.55627601],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ]]), array([[-3.82584898, -0.37741176,  3.42049957],
       [ 1.6438193 ,  4.31515397, -5.64221711],
       [-3.41783597,  2.96319377, -4.53657387],
       [-1.75878797, -4.98337268, -3.82963893],
       [-2.88453527, -4.81680508,  1.05100713]]))
(16.751182563381107, array([[  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.  

In [95]:
a = np.array([1,2,3])


In [96]:
b = (np.tile(a, (15,1)))

In [103]:
b[[1,2,3]] += [[1,1,1], [1,1,1], [1,1,1]]

In [104]:
b


array([[1, 2, 3],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [137]:
test_word2vec()


==== Gradient check for skip-gram ====
Gradient check passed!
Gradient check passed!

==== Gradient check for CBOW      ====
Gradient check passed!
Gradient check passed!

=== Results ===
(11.166109001533979, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-1.26947339, -1.36873189,  2.45158957],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.41045956,  0.18834851,  1.43272264],
       [ 0.38202831, -0.17530219, -1.33348241],
       [ 0.07009355, -0.03216399, -0.24466386],
       [ 0.09472154, -0.04346509, -0.33062865],
       [-0.13638384,  0.06258276,  0.47605228]]))
(15.640206709941292, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-4.53657178, -1.4244085 , -1.21818087],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.69148188,  0.31730185,  2.4136402

In [138]:
from q3_sgd import sanity_check as sgd_check

In [147]:
sgd_check()

Running sanity checks...
iter 100: 0.004578
iter 200: 0.004353
iter 300: 0.004136
iter 400: 0.003929
iter 500: 0.003733
iter 600: 0.003546
iter 700: 0.003369
iter 800: 0.003200
iter 900: 0.003040
iter 1000: 0.002888
test 1 result: 8.41483678608e-10
iter 100: 0.000000
iter 200: 0.000000
iter 300: 0.000000
iter 400: 0.000000
iter 500: 0.000000
iter 600: 0.000000
iter 700: 0.000000
iter 800: 0.000000
iter 900: 0.000000
iter 1000: 0.000000
test 2 result: 0.0
iter 100: 0.041205
iter 200: 0.039181
iter 300: 0.037222
iter 400: 0.035361
iter 500: 0.033593
iter 600: 0.031913
iter 700: 0.030318
iter 800: 0.028802
iter 900: 0.027362
iter 1000: 0.025994
test 3 result: -2.52445103582e-09



In [155]:
import warnings
warnings.warn("Sample warning")

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: UserWarning: Sample warning
  from ipykernel import kernelapp as app


In [151]:
10**-2

0.01